spring:
  activiti:
    database-schema-update: false
    history-level: full
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.82.12.238:3307/activiti?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true&useSSL=false
      username: meUser
      password: mepassword

server:
  port: 8050

logging:
  level:
    org.activiti.engine.impl.persistence.entity: trace
